//
// QCDLoop + Kokkos 2025
//
// Authors: Reet Barik      : rbarik@anl.gov
//          Taylor Childers : jchilders@anl.gov
//
// Double-double precision version of kokkosMaths (DDFUN backend, ql::ddfun::).
// Portable across all Kokkos backends (CUDA / HIP / SYCL / OpenMP / Serial).

#pragma once

#include <math.h>
#include <type_traits>

#include "dd_math.hpp"
#include "dd_complex.hpp"

namespace ql
{
    using complex = ql::ddfun::ddcomplex;

    template<typename T>
    struct Constants {

        // Number of Chebyshev coefficients for ddilog (must match coeffs array in _C)
        KOKKOS_INLINE_FUNCTION
        static constexpr int _num_C() { return 43; }

        KOKKOS_INLINE_FUNCTION
        static T _C(int i) {
            // DD-encoded Chebyshev coefficients (43 terms) — generated by scripts/gen_dd_constants
            const T coeffs[43] = {
                ql::ddfun::make_dd(0x3fdb849409b3171fULL, 0xbc61d08606ea8094ULL),  // C[0]
                ql::ddfun::make_dd(0x3fda39817bf08e86ULL, 0xbc708f7bc068d1c3ULL),  // C[1]
                ql::ddfun::make_dd(0xbf9308d8ddfc0d4fULL, 0xbbf1bfa97f0c6941ULL),  // C[2]
                ql::ddfun::make_dd(0x3f57e13e5937f304ULL, 0xbbf969cc9f4aca3cULL),  // C[3]
                ql::ddfun::make_dd(0xbf22bfb0166773adULL, 0xbbbf2b286495c7dbULL),  // C[4]
                ql::ddfun::make_dd(0x3ef0a7ded9492ebfULL, 0x3b8490eeb0ccf2dcULL),  // C[5]
                ql::ddfun::make_dd(0xbec0011368001ad0ULL, 0x3b5b7a1b649f1629ULL),  // C[6]
                ql::ddfun::make_dd(0x3e903cb34eb28bc7ULL, 0xbb361a0a29ecc366ULL),  // C[7]
                ql::ddfun::make_dd(0xbe6124e51374ab95ULL, 0xbadc3fca1c01886fULL),  // C[8]
                ql::ddfun::make_dd(0x3e32a9df9d2cf366ULL, 0x3ab088ab369bb63bULL),  // C[9]
                ql::ddfun::make_dd(0xbe04d08a1a397c33ULL, 0xba735fddea7b4414ULL),  // C[10]
                ql::ddfun::make_dd(0x3dd7ac399e1b3a10ULL, 0x3a7ac270c61db429ULL),  // C[11]
                ql::ddfun::make_dd(0xbdab5cf6e979608fULL, 0xba4c202e357f882eULL),  // C[12]
                ql::ddfun::make_dd(0x3d8008088ec141cbULL, 0x3a24e69a8e63ff1fULL),  // C[13]
                ql::ddfun::make_dd(0xbd53011b4100aa8bULL, 0x39f924a9ad769bbcULL),  // C[14]
                ql::ddfun::make_dd(0x3d26c16ffed236b0ULL, 0x39c2c37e09229bd6ULL),  // C[15]
                ql::ddfun::make_dd(0xbcfb7c91e18c27c2ULL, 0xb978259da7d88ef0ULL),  // C[16]
                ql::ddfun::make_dd(0x3cd0ba8c8168432dULL, 0xb97f38b87f87b056ULL),  // C[17]
                ql::ddfun::make_dd(0xbca48079ae714341ULL, 0x3938662e035d673fULL),  // C[18]
                ql::ddfun::make_dd(0x3c794781af84652eULL, 0xb8df1ac5eacaaed6ULL),  // C[19]
                ql::ddfun::make_dd(0xbc4f573ccb1c7256ULL, 0x38c0cea00a8fc228ULL),  // C[20]
                ql::ddfun::make_dd(0x3c23861c064989cfULL, 0x38b9858a8264065fULL),  // C[21]
                ql::ddfun::make_dd(0xbbf86f1e6a569636ULL, 0x389bb8f28a19ffd1ULL),  // C[22]
                ql::ddfun::make_dd(0x3bceb443cb9151fdULL, 0x3865a1ff47ab26b3ULL),  // C[23]
                ql::ddfun::make_dd(0xbba35d221a0bf286ULL, 0xb8416f4aacf5c45eULL),  // C[24]
                ql::ddfun::make_dd(0x3b7881fe4d78bb1dULL, 0xb815c2b246c97c6fULL),  // C[25]
                ql::ddfun::make_dd(0xbb4f1dd5a2fc7960ULL, 0x37cad4f86fb2f160ULL),  // C[26]
                ql::ddfun::make_dd(0x3b23cfc3b677dfe1ULL, 0xb7a9e8649f3ef895ULL),  // C[27]
                ql::ddfun::make_dd(0xbaf94bd49715a0bdULL, 0x379861cde38fb0f0ULL),  // C[28]
                ql::ddfun::make_dd(0x3ad030bf7644b683ULL, 0xb77791ac8f6b139dULL),  // C[29]
                ql::ddfun::make_dd(0xbaa4c60ebb342bc8ULL, 0xb74eefcd74311948ULL),  // C[30]
                ql::ddfun::make_dd(0x3a7ab68a8997736cULL, 0x370ce9ceb1387136ULL),  // C[31]
                ql::ddfun::make_dd(0xba5135f1c3d828d0ULL, 0xb6fa3081db7911a2ULL),  // C[32]
                ql::ddfun::make_dd(0x3a2638548f4222a9ULL, 0x36c71521bbeedd19ULL),  // C[33]
                ql::ddfun::make_dd(0xb9fcbd5755a6d334ULL, 0xb683ea3a0ae4390aULL),  // C[34]
                ql::ddfun::make_dd(0x39d29e317705e440ULL, 0xb66845af574cbaefULL),  // C[35]
                ql::ddfun::make_dd(0xb9a82938b74d8e42ULL, 0x3645649ddd2643d2ULL),  // C[36]
                ql::ddfun::make_dd(0x397f67066462e3f2ULL, 0xb5f576d5d6bcf559ULL),  // C[37]
                ql::ddfun::make_dd(0xb9546fcb719bbdcfULL, 0x35f7299ec8a3fdadULL),  // C[38]
                ql::ddfun::make_dd(0x392aa30fd9290536ULL, 0x35ca760528288e40ULL),  // C[39]
                ql::ddfun::make_dd(0xb90161be6c7ded9aULL, 0xb573d0e195f44a48ULL),  // C[40]
                ql::ddfun::make_dd(0x38d6b6861e77d634ULL, 0x356bfef4bcfab248ULL),  // C[41]
                ql::ddfun::make_dd(0xb8adb6cee2774df0ULL, 0x354562db4ea6970aULL)   // C[42]
            };
            return coeffs[i];
        }

        // Number of Bernoulli coefficients for li2series (must match coeffs array in _B)
        KOKKOS_INLINE_FUNCTION
        static constexpr int _num_B() { return 25; }

        KOKKOS_INLINE_FUNCTION
        static T _B(int i) {
            // DD-encoded Bernoulli coefficients (25 terms) — generated by scripts/gen_dd_constants
            const T coeffs[25] = {
                ql::ddfun::make_dd(0x3f9c71c71c71c71cULL, 0x3c3c71c71c71c71cULL),  // B[0]
                ql::ddfun::make_dd(0xbf323456789abcdfULL, 0xbb723456789abcdfULL),  // B[1]
                ql::ddfun::make_dd(0x3ed3d079fb6ef3e3ULL, 0x3b4adb9557cf6495ULL),  // B[2]
                ql::ddfun::make_dd(0xbe78a86a49f629d1ULL, 0x3b19b054db95c888ULL),  // B[3]
                ql::ddfun::make_dd(0x3e204d7f65caf373ULL, 0xbac6cd713a6fb97aULL),  // B[4]
                ql::ddfun::make_dd(0xbdc658a4b8f16a75ULL, 0x3a4e68e462783b95ULL),  // B[5]
                ql::ddfun::make_dd(0x3d6f63f1e311ac24ULL, 0x39ffbe3b291e07ccULL),  // B[6]
                ql::ddfun::make_dd(0xbd16731c59dbd7deULL, 0xb9b968f9b1e5279dULL),  // B[7]
                ql::ddfun::make_dd(0x3cc04805fdce7819ULL, 0xb93eaa712fafb00dULL),  // B[8]
                ql::ddfun::make_dd(0xbc67e168b15d7793ULL, 0x38eb10f259d71460ULL),  // B[9]
                ql::ddfun::make_dd(0x3c11ac70a7618abdULL, 0xb8bf797e5f69a3dbULL),  // B[10]
                ql::ddfun::make_dd(0xbbba5bf70e5eefd2ULL, 0xb85e19ea7e4b4c05ULL),  // B[11]
                ql::ddfun::make_dd(0x3b63c8881c2dd68cULL, 0x37f33be648f8a92aULL),  // B[12]
                ql::ddfun::make_dd(0xbb0ddc14c868f2dbULL, 0xb76503d00b03c1baULL),  // B[13]
                ql::ddfun::make_dd(0x3ab6a45025fc86a2ULL, 0x375b9645dce4fc4aULL),  // B[14]
                ql::ddfun::make_dd(0xba613d916dfdf3ecULL, 0x37082c02b91f6e2cULL),  // B[15]
                ql::ddfun::make_dd(0x3a0a5a26479b86c0ULL, 0xb6a24fe24f17e162ULL),  // B[16]
                ql::ddfun::make_dd(0xb9b434a4aab89c3dULL, 0xb64e9ad4ef4e6d6fULL),  // B[17]
                ql::ddfun::make_dd(0x395f138b40614ceaULL, 0x35f312f1b88436c6ULL),  // B[18]
                ql::ddfun::make_dd(0xb907f5f58356eed3ULL, 0xb5ad1122bddef73cULL),  // B[19]
                ql::ddfun::make_dd(0x38b284be7dea0f2dULL, 0xb54a892964d5f581ULL),  // B[20]
                ql::ddfun::make_dd(0xb85cafd4d179e626ULL, 0xb4db92ba45b7ea02ULL),  // B[21]
                ql::ddfun::make_dd(0x380643613376ba51ULL, 0x3489f1f3b8056581ULL),  // B[22]
                ql::ddfun::make_dd(0xb7b14f2ea64ff5d8ULL, 0xb429bd0e711af996ULL),  // B[23]
                ql::ddfun::make_dd(0x375af5da8e3360cdULL, 0x33f5ccf27901f02bULL)   // B[24]
            };
            return coeffs[i];
        }

        template<typename TOutput, typename TMass, typename TScale>
        KOKKOS_INLINE_FUNCTION static T _qlonshellcutoff() {
            return T(1e-20);
        }

        KOKKOS_INLINE_FUNCTION
        static T _pi() {
            return ql::ddfun::dd_pi();
        }

        KOKKOS_INLINE_FUNCTION
        static T _pi2() {
            return _pi() * _pi();
        }

        template<typename TOutput, typename TMass, typename TScale>
        KOKKOS_INLINE_FUNCTION static T _pio3() {
            return _pi() / ql::Constants<TScale>::_three();
        }

        template<typename TOutput, typename TMass, typename TScale>
        KOKKOS_INLINE_FUNCTION static T _pio6() {
            return _pi() / ql::Constants<TScale>::_six();
        }

        template<typename TOutput, typename TMass, typename TScale>
        KOKKOS_INLINE_FUNCTION static T _pi2o3() {
            return _pi() * _pio3<TOutput, TMass, TScale>();
        }

        template<typename TOutput, typename TMass, typename TScale>
        KOKKOS_INLINE_FUNCTION static T _pi2o6() {
            return _pi() * _pio6<TOutput, TMass, TScale>();
        }

        template<typename TOutput, typename TMass, typename TScale>
        KOKKOS_INLINE_FUNCTION static T _pi2o12() {
            return _pi2() / ql::Constants<TScale>::_twelve();
        }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _zero() { return T(0.0); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _half() { return T(0.5); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _one() { return T(1.0); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _two() { return T(2.0); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _three() { return T(3.0); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _four() { return T(4.0); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _five() { return T(5.0); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _six() { return T(6.0); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _ten() { return T(10.0); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _twelve() { return T(12.0); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _eps() { return T(1e-12); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _eps4() { return T(1e-4); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _eps7() { return T(1e-7); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _eps10() { return T(1e-10); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _eps14() { return T(1e-14); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _eps15() { return T(1e-15); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _xloss() { return T(0.125); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _neglig() { return T(1e-28); }

        KOKKOS_INLINE_FUNCTION
        static constexpr T _reps() { return T(1e-30); }

        template<typename TOutput, typename TMass, typename TScale>
        KOKKOS_INLINE_FUNCTION static TOutput _2ipi() {
            return TOutput{Constants<TScale>::_zero(), Constants<TScale>::_two() * Constants<TScale>::_pi()};
        }

        template<typename TOutput, typename TMass, typename TScale>
        KOKKOS_INLINE_FUNCTION static TOutput _ipio2() {
            return TOutput{Constants<TScale>::_zero(), Constants<TScale>::_pi() * Constants<TScale>::_half()};
        }

        template<typename TOutput, typename TMass, typename TScale>
        KOKKOS_INLINE_FUNCTION static TOutput _ipi() {
            return TOutput{Constants<TScale>::_zero(), Constants<TScale>::_pi()};
        }

        template<typename TOutput, typename TMass, typename TScale>
        KOKKOS_INLINE_FUNCTION static TOutput _ieps() {
            return TOutput{Constants<TScale>::_zero(), Constants<TScale>::_reps()};
        }

        template<typename TOutput, typename TMass, typename TScale>
        KOKKOS_INLINE_FUNCTION static TOutput _ieps2() {
            return TOutput{Constants<TScale>::_zero(), Constants<TScale>::_reps() * Constants<TScale>::_reps()};
        }

        template<typename TOutput, typename TMass, typename TScale>
        KOKKOS_INLINE_FUNCTION static TOutput _ieps50() {
            return TOutput{Constants<TScale>::_zero(), TScale(1e-50)};
        }
    };

    template<typename TOutput, typename TMass, typename TScale>
    KOKKOS_INLINE_FUNCTION TOutput kPow(TOutput const& base, int const& exponent) {
        TOutput temp = TOutput(1.0);

        for (int i = 0; i < exponent; i++)
            temp *= base;

        return temp;
    }

    template<typename TOutput, typename TMass, typename TScale>
    KOKKOS_INLINE_FUNCTION TMass kPow(TMass const& base, int const& exponent) {
        TMass temp = TMass(1.0);

        for (int i = 0; i < exponent; i++)
            temp *= base;

        return temp;
    }

    // Math dispatch functions - base templates
    template<typename T>
    KOKKOS_INLINE_FUNCTION
    T kAbs(T const& x) {
        return Kokkos::abs(x);
    }

    template<typename T>
    KOKKOS_INLINE_FUNCTION
    T kLog(T const& x) {
        return Kokkos::log(x);
    }

    template<typename T>
    KOKKOS_INLINE_FUNCTION
    T kSqrt(T const& x) {
        return Kokkos::sqrt(x);
    }

    // DD specializations
    template<>
    KOKKOS_INLINE_FUNCTION
    ql::ddfun::ddouble kAbs(ql::ddfun::ddouble const& x) {
        return ql::ddfun::abs(x);
    }

    template<>
    KOKKOS_INLINE_FUNCTION
    ql::ddfun::ddouble kLog(ql::ddfun::ddouble const& x) {
        return ql::ddfun::log(x);
    }

    template<>
    KOKKOS_INLINE_FUNCTION
    ql::ddfun::ddouble kSqrt(ql::ddfun::ddouble const& x) {
        return ql::ddfun::sqrt(x);
    }

    // Overloads for ddcomplex
    KOKKOS_INLINE_FUNCTION
    ql::ddfun::ddouble kAbs(ql::ddfun::ddcomplex const& z) {
        return ql::ddfun::abs(z);
    }

    KOKKOS_INLINE_FUNCTION
    ql::ddfun::ddcomplex kLog(ql::ddfun::ddcomplex const& z) {
        return ql::ddfun::log(z);
    }

    KOKKOS_INLINE_FUNCTION
    ql::ddfun::ddcomplex kSqrt(ql::ddfun::ddcomplex const& z) {
        return ql::ddfun::sqrt(z);
    }

    KOKKOS_INLINE_FUNCTION
    ql::ddfun::ddcomplex kConj(ql::ddfun::ddcomplex const& z) {
        return ql::ddfun::conj(z);
    }

    template<typename TOutput, typename TMass, typename TScale>
    KOKKOS_INLINE_FUNCTION bool iszero(TScale const& x) {
        return (ql::kAbs(x) < ql::Constants<TScale>::template _qlonshellcutoff<TOutput, TMass, TScale>()) ? true : false;
    }

    KOKKOS_INLINE_FUNCTION ql::ddfun::ddouble Imag(ql::ddfun::ddouble const& /*x*/) {
        return ql::ddfun::ddouble(0.0);
    }

    KOKKOS_INLINE_FUNCTION ql::ddfun::ddouble Imag(ql::ddfun::ddcomplex const& x) {
        return x.imag();
    }

    KOKKOS_INLINE_FUNCTION ql::ddfun::ddouble Real(ql::ddfun::ddouble const& x) {
        return x;
    }

    KOKKOS_INLINE_FUNCTION ql::ddfun::ddouble Real(ql::ddfun::ddcomplex const& x) {
        return x.real();
    }

    KOKKOS_INLINE_FUNCTION ql::ddfun::ddouble Sign(ql::ddfun::ddouble const& x) {
        const ql::ddfun::ddouble zero = ql::Constants<ql::ddfun::ddouble>::_zero();
        const ql::ddfun::ddouble one  = ql::Constants<ql::ddfun::ddouble>::_one();
        if (zero < x) {
            return one;
        } else if (x < zero) {
            return -one;
        } else {
            return zero;
        }
    }

    KOKKOS_INLINE_FUNCTION ql::ddfun::ddcomplex Sign(ql::ddfun::ddcomplex const& x) {
        return x / ql::kAbs(x);
    }

    KOKKOS_INLINE_FUNCTION ql::ddfun::ddouble Max(ql::ddfun::ddouble const& a, ql::ddfun::ddouble const& b) {
        if (ql::kAbs(a) > ql::kAbs(b))
            return a;
        else
            return b;
    }

    KOKKOS_INLINE_FUNCTION ql::ddfun::ddcomplex Max(ql::ddfun::ddcomplex const& a, ql::ddfun::ddcomplex const& b) {
        if (ql::kAbs(a) > ql::kAbs(b))
            return a;
        else
            return b;
    }

    KOKKOS_INLINE_FUNCTION ql::ddfun::ddouble Min(ql::ddfun::ddouble const& a, ql::ddfun::ddouble const& b) {
        if (ql::kAbs(a) > ql::kAbs(b))
            return b;
        else
            return a;
    }

    KOKKOS_INLINE_FUNCTION ql::ddfun::ddcomplex Min(ql::ddfun::ddcomplex const& a, ql::ddfun::ddcomplex const& b) {
        if (ql::kAbs(a) > ql::kAbs(b))
            return b;
        else
            return a;
    }

    KOKKOS_INLINE_FUNCTION ql::ddfun::ddouble Htheta(ql::ddfun::ddouble const& x) {
        return ql::ddfun::ddouble(0.5) * (ql::ddfun::ddouble(1.0) + ql::Sign(x));
    }

}
